### ISSUE TITLE
Add some manner of font rendering capability

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/outcurses#43]
We ought be able to generate big text (i.e. more than one character cell per character) more or less according to a chosen font. The way to do this ideally in my mind would be to use Pango to render a font into an image buffer, then feed that into our image routines (so this depends on #18 ). If that ends up being generally unreadable, though, we'll have to take a different approach.

We ought be able to determine whether it'll work without actually coding up the Pango -- just get some suitable text in the GIMP, and load it as an image.

**Comment by dankamongmen** [comment]
@jart (hey Justine!) did some work in her python-fabulous module https://jart.github.io/fabulous/. there only appears to be one font, and it appears to be built up from unicode half blocks using truecolor.

**Comment by dankamongmen** [comment]
the above certainly looks better than e.g. figlet, and i think serves as a suitable baseline

**Comment by jart** [comment]
One thing you could try are DEC double lines, e.g. `printf '\e#3hello\n\e#4hello\n'`.

**Comment by dankamongmen** [comment]
This is much more of a [notcurses](https://github.com/dankamongmen/notcurses) thing, now that that project is going on. We want control of the full rendering pipeline to do this properly.
