### ISSUE TITLE
Integrate "direct color" / non-indexed 24bit color atop ncurses

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/outcurses#56]
first, a comment on nomenclature: these terms are subject to some disagreement. *For the purpose of this bug*, "TrueColor" will refer to "24-bit color making use of an 8-bit palette, which might be dynamic", "DirectColor" will refer to "24-bit color making use of 24-bit RGB specification", "256-indexed color" will be considered synonymous with "TrueColor", and "non-indexed" will be considered synonymous with "DirectColor". Note that these do not necessarily correspond to definitions in X11R6's "[Visual types](https://pubs.opengroup.org/onlinepubs/9609699/toc.pdf)" (§2.5.5), nor do they necessarily correspond to NCURSES nor any terminal's terminology, nor do they necessarily correspond to any ISO 8613-6 (ITU T.416) definitions.

**the story thus far....**

NCURSES supports, on terminals which support it (inspect the output of `tput colors`), a 256-index palette composed of arbitrary 24-bit colors (8 bits each of R, G, and B). These colors can then be used as foregrounds and backgrounds in up to 32K colorpairs. NB: some terminals seem to indicate 64K colorpairs according to both `tput pairs` and `COLOR_PAIRS`, but will error out (#36) when `init_extended_pair()` is used with a pair above 32767 (sometimes it works fine; I've not yet figured this out; documentation seems to suggest a hard 32767 maximum based on the size of signed `int`s). These are known as "extended colors". This is all spelled out in the [NCURSES FAQ](https://invisible-island.net/ncurses/ncurses.faq.html#xterm_16MegaColors), which is _absolutely mandatory_ background reading. Note that the use of "color pairs" seems a pure NCURSESism, arising from terminals which did not allow the foreground and background to be specified distinctly:

> Because some terminal types did not provide a way to set foreground and background colors independently, the concept of color pairs was introduced.

Reading the NCURSES documentation, it seems clear that backwards compatability, standards conformance, and wide hardware support (in terms of hardware diversity, not necessarily number of users) are major design goals. This is all noble. Furthermore (quoting again the NCURSES FAQ, 2019-11-14):

> Using the ncurses 6 ABI, you have 256 colors, or 32767 pairs (the limit for a signed 16-bit number). That limit is good enough for realistic applications, which could not have that many character cells on a screen simultaneously (unless of course, using 1-pixel fonts to pretend to draw graphics, e.g., AA-lib). Since ncurses is used to draw text, that is not a valid issue.

and

> That number of colors exceeds by a couple of orders of magnitude the ability of anyone to discern the differences and rely on those distinctions to aid them in viewing text.

Since outcurses seeks to be a blend of graphics and TUI, this doesn't really apply to us; these colors *are* a valid issue. I have furthermore demonstrated to my satisfaction that, for many images, it is impossible to achieve the visual quality of e.g. `viu` nor the TCT ("true color terminal") output of `mpv` without employing more than 256 simultaneous 24-bit colors. See #45 and #18 for more details.

Conclusion: NCURSES can and probably ought indeed stay above the fray until necessary escape sequences and semantics have been standardized and widely implemented. Unfortunately, we cannot achieve our goals, which include visibly appealing background graphics and animation effects in TUI programs _on modern terminals_ optimizing for _audience size_ rather than _diversity of audience hardware_. I hope this is an accurate and fair summation.

The NCURSES FAQ goes on about people with similar goals:

> A small minority of terminals support an additional interpretation of SGR 38 and 48 alluded to in
ISO 8613-6 as direct colour...Bypassing the limits which can be derived from the terminal database (and veering off into the swamp of hard-coded behavior), the idle spectator might ask “why not add a special ad hoc interface to (somehow) just do it? The problem is that you cannot “just do it”—both ncurses and s-lang do optimization to address their legitimate users.

The "small minority" here once again seems to prioritize "terminal diversity" over "terminal instances", which is NCURSES's prerogative. The "legitimate users" of outcurses are primarily people making use of modern terminals on workstation and mobile UNIX machines, quite possibly remotely over SSH, desirous of -- let's admit it -- eye candy. Our goals are silly in the context of NCURSES, but not silly for us. Breaking necessary optimizations, however, is very undesirable.

With that said, direct color can certainly be run effectively over an SSH connection. The following screencap is taken from a terminal SSH'd into my office workstation, making the trip over my personal VPN. The terminal emulator (`xfce4-terminal`) is running at a size of 239x64, pretty big:

![mpv-tct-demo](https://user-images.githubusercontent.com/143473/68885089-798ed200-06e2-11ea-8636-ae8af23156f7.jpg)

this works just fine without any noticeable lag (admittedly, my terminal emulator is eating rather more CPU than I'd like). But that's a screen of a single, non-occluded output plane. Our goal is to make such vivid graphics available in a PANELed context.

So our challenge becomes:

 * make some manner of 24-bit DirectColor available to our users through our API, implemented on the backend using escape codes, external to NCURSES, while
 * continuing to support the NCURSES functionality we know and love, particularly the Panels API, disrupting NCURSES as little as possible

For instance, what happens when we `move_panel()` an entirely NCURSES-drawn PANEL across the width of an underlying PANEL in which we have used escape codes directly? NCURSES couldn't know how to restore the uncovered text, since we didn't color it through NCURSES. We would be responsible for the redraw...but that doesn't honestly seem unworkable, so long as we do know how and what to repaint?

A bigger issue would involve getting our colors into the draw cycle. NCURSES draws onto its virtual screen, then (possibly following many virtual screen updates) updates the physical one. We rely on this for any kind of decent, flicker-free performance. Would we be able to inject our escape codes into the NCURSES drawing routine, or would we need apply them immediately after a `doupdate()`? Furthermore, would we need apply them wholly without NCURSES routines--i.e., would we need move the cursor with termios rather than the more pleasant NCURSES routines? Probably. This might admittedly be a major problem. Before launching any major effort, some experimentation will be necessary here.

I think there's a good chance we can get this done, but it's not guaranteed. I'd like to get Thomas E. Dickey to take a look at this writeup. It'll almost certainly piss him off a little, but his feedback would be invaluable. Of course, the 16 million color section of his FAQ concludes:

> Without significant revision, there is nothing more to discuss.

I wrote this bug up after last night reading Lexi Summer Hale's essay "[on terminal control](http://xn--rpa.cc/irl/term.html)". It would probably be useful to reach out to her as well, likely pissing her off from a different direction:

> you philistines won't stop using ncurses and oh my god WHY ARE WE STILL USING NCURSES IT IS THE TWENTY FIRST FUCKING CENTURY

So I'll reach out to both of these fine minds, and report back with any information they might provide. What we can do will really shape the "wow!" factor of our Thanksgiving demo.

**Comment by dankamongmen** [comment]
I've privately sent Grandmaster Dickey a suitably sycophantic email, and hopefully might get some good feedback there.

**Comment by dankamongmen** [comment]
I started down the road of shimming ncurses, and even considered some live-patching via eBPF. That's clearly madness, and I need get outside more. The more I think about it, the more this paragraph of @velartrill's essay rings true:

> yes, ncurses supplies features like window-drawing and region invalidation (to avoid terminal flicker) that are much harder to implement yourself. no, you shouldn't have to implement it yourself. there should be a modern library to replace curses using the capabilities outlined here. but i swear to god developers have so completely forgotten how terminals work that i might be one of a handful of people left on earth who actually has the knowledge to, so they all just layer their bullshit on top of ncurses (which should never have survived the '90s) instead and it's ｍａｄｄｅｎｉｎｇ．

If I want to do this right, it may well be the case that I need write that library, and need just internalize that hard fucking fact, ugh.

**Comment by velartrill** [comment]
for what it's worth, if you'd be interested in collaborating on a library to supply ncurses-like functionality with modern techniques i'd be happy to help out. the good news is that vast majority of terminals today, from xterm to Konsole to kitty to anything that uses libvte, have informally standardized on same escape codes for most things these days, and the ones that don't, like urxvt, simply lack support for direct color. you're correct that trying to interlace with ncurses is, shall we say, cursed.

we've been planning on adding some lightweight, modern terminal control features to [libk](https://c.hale.su/libk) so we could kill two birds with one stone and i could probably get a few more eyes on the problem at the very least. (libk is agpl but i'd be fine with dual-licensing any code my team contributes.)

**Comment by dankamongmen** [comment]
> for what it's worth, if you'd be interested in collaborating on a library to supply ncurses-like functionality with modern techniques i'd be happy to help out. the good news is that vast majority of terminals today, from xterm to Konsole to kitty to anything that uses libvte, have informally standardized on same escape codes for most things these days, and the ones that don't, like urxvt, simply lack support for direct color. you're correct that trying to interlace with ncurses is, shall we say, cursed.
> 
> we've been planning on adding some lightweight, modern terminal control features to [libk](https://c.hale.su/libk) so we could kill two birds with one stone and i could probably get a few more eyes on the problem at the very least. (libk is agpl but i'd be fine with dual-licensing any code my team contributes.)

for what it's worth, if you'd be interested in collaborating on a library to supply ncurses-like functionality with modern techniques i'd be happy to help out. the good news is that vast majority of terminals today, from xterm to Konsole to kitty to anything that uses libvte, have informally standardized on same escape codes for most things these days, and the ones that don't, like urxvt, simply lack support for direct color. you're correct that trying to interlace with ncurses is, shall we say, cursed.

we've been planning on adding some lightweight, modern terminal control features to [libk](https://c.hale.su/libk) so we could kill two birds with one stone and i could probably get a few more eyes on the problem at the very least. (libk is agpl but i'd be fine with dual-licensing any code my team contributes.)

nice to meet you, @velartrill ; I spent about an hour last night going through your site, and (strident leftism aside) suspect that we feel similarly about a lot of things :). hack on!

**Comment by jart** [comment]
I wouldn't waste my time with ncurses. It doesn't do anything. Optimal cursor motion made sense in the days of 300 baud modem connections. But today it can often be harmful since bouncing around like that in your rendering algorithm means non-local memory access patterns that defeat caches and branch predictors. The rest of ncurses is just a second rate gui framework, that'd probably make microsofties gag if they ever saw it. The only things you need are ioctl() to pass the magnum to the kernel that gets you out of icanon, and then \e[y;xH to move the cursor. ANSI X3.64-1979 is nearly as universal as ASCII. Even old MS-DOS and Microsoft Windows support all the essential codes that are needed.

**Comment by velartrill** [comment]
unforunately unless all your users are using `kitty` you do need *some* of the features ncurses supplies. in my essay that @dankamongmen linked there's a sample program at the bottom you can try running to see how bad flicker is when you re-render the entire screen at each update. region invalidation is the main thing a new library needs to be written for, tho there are also other small (but easy) things like using termios to extract the height and width of the terminal, without which you can't do much useful.

ideally in The Year of Our Lord Two Thousand And Nineteen we'd be moving away from VT emulators in the first place towards proper GUI terminals, but alas libtcod seems to be the best we're going to get in that space.

**Comment by dankamongmen** [comment]
I spoke with Thomas E. Dickey, and conclude that there is no way to do this that doesn't require more effort, with a lesser chance of maintainable success, than building up something *ab initio* or, at the very least, sans curses.

Fair enough.

**Comment by jart** [comment]
@velartrill Lexi, I got a chance to read your blog. Your rendering code works really well. Flicking was the fault of the stdio library. It was dispatching too many system calls, according to strace. Thankfully the C library provides a solution to the difficulties it introduces. `open_memstream` seems to be just what you need. Give this code a try: https://gist.github.com/jart/b9104dd959f2dd65ecdcb5ce69d332e6 I added a couple more things too, that I hope you'll enjoy, such as variable monospace widths.

**Comment by velartrill** [comment]
@jart well i'll be damned. tested your code in a handful of terminals and you're absolutely right. even in xterm it behaves flawlessly. hell, it barely flickers even in a text-mode console. this is extremely good to know. (i think probably the best approach to this rather than using a memstream would be to allocate a buffer based on the current size of the terminal and reallocate on SIGWINCH if necessary, but that's armchair optimization; i haven't tested it myself.)

**Comment by dankamongmen** [comment]
`open_wmemstream` in our case :D
